// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/weather_info/domain/entities/weather_local_info_response_entity/clouds_local_entity.dart';
import 'features/weather_info/domain/entities/weather_local_info_response_entity/coordinate_local_entity.dart';
import 'features/weather_info/domain/entities/weather_local_info_response_entity/main_weather_info_local_entity.dart';
import 'features/weather_info/domain/entities/weather_local_info_response_entity/sunset_sunrise_local_entity.dart';
import 'features/weather_info/domain/entities/weather_local_info_response_entity/weather_description_local_entity.dart';
import 'features/weather_info/domain/entities/weather_local_info_response_entity/weather_local_info_entity.dart';
import 'features/weather_info/domain/entities/weather_local_info_response_entity/weather_theme_local_entity.dart';
import 'features/weather_info/domain/entities/weather_local_info_response_entity/wind_info_local_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 659175198335478770),
      name: 'CloudsLocalEntity',
      lastPropertyId: const IdUid(2, 3628467804910156124),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2721111473364878454),
            name: 'all',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(2, 3628467804910156124),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 4749030018044070196),
      name: 'CoordinateLocalEntity',
      lastPropertyId: const IdUid(3, 574756828556962182),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4944836938362846981),
            name: 'lon',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(2, 4062326517946898312),
            name: 'lat',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 574756828556962182),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 150152867497418059),
      name: 'MainWeatherInfoLocalEntity',
      lastPropertyId: const IdUid(7, 4847645746641927583),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7846220782551510999),
            name: 'temp',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(2, 2540920901178068352),
            name: 'feelsLike',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3915479635085916058),
            name: 'tempMin',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8584998259690716389),
            name: 'tempMax',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 6337243429144738925),
            name: 'pressure',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 3769601041942211231),
            name: 'humidity',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4847645746641927583),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 2381800942354481187),
      name: 'SunsetSunriseLocalEntity',
      lastPropertyId: const IdUid(5, 1147005129194528628),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1347442623250245756),
            name: 'type',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(2, 5457562273006794065),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(3, 3197389866726461945),
            name: 'country',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5735296651796150739),
            name: 'sunrise',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 1147005129194528628),
            name: 'sunset',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(5, 2128202574536264139),
      name: 'WeatherDescriptionLocalEntity',
      lastPropertyId: const IdUid(4, 7816458642974796560),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5189310158225736837),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3842688152102093354),
            name: 'main',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5015197835503966351),
            name: 'description',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7816458642974796560),
            name: 'icon',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(6, 7214186939867233624),
      name: 'WeatherInfoLocalEntity',
      lastPropertyId: const IdUid(9, 6759570401098470137),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7073220170814968776),
            name: 'mainId',
            type: 11,
            flags: 520,
            indexId: const IdUid(1, 7653145386604242201),
            relationTarget: 'MainWeatherInfoLocalEntity'),
        ModelProperty(
            id: const IdUid(2, 8658481711114297058),
            name: 'visibility',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1134564110364817476),
            name: 'windId',
            type: 11,
            flags: 520,
            indexId: const IdUid(2, 2143001172414270620),
            relationTarget: 'WindInfoLocalEntity'),
        ModelProperty(
            id: const IdUid(4, 1485642820154883651),
            name: 'cloudsId',
            type: 11,
            flags: 520,
            indexId: const IdUid(3, 6271925479728100989),
            relationTarget: 'CloudsLocalEntity'),
        ModelProperty(
            id: const IdUid(5, 4046970696962758301),
            name: 'dt',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 5302646288405915111),
            name: 'sysId',
            type: 11,
            flags: 520,
            indexId: const IdUid(4, 7517837576210169302),
            relationTarget: 'SunsetSunriseLocalEntity'),
        ModelProperty(
            id: const IdUid(7, 7960815754384568050),
            name: 'timeZone',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 7035202171554225647),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(9, 6759570401098470137),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(1, 9129959591420871614),
            name: 'weather',
            targetId: const IdUid(5, 2128202574536264139))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(7, 19391231403855530),
      name: 'WeatherThemeLocalEntity',
      lastPropertyId: const IdUid(1, 4359170196303042200),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4359170196303042200),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(8, 853939006241248506),
      name: 'WindInfoLocalEntity',
      lastPropertyId: const IdUid(3, 8506926639109336361),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8183063618363603897),
            name: 'speed',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(2, 6917294319572803479),
            name: 'deg',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 8506926639109336361),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(8, 853939006241248506),
      lastIndexId: const IdUid(4, 7517837576210169302),
      lastRelationId: const IdUid(1, 9129959591420871614),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    CloudsLocalEntity: EntityDefinition<CloudsLocalEntity>(
        model: _entities[0],
        toOneRelations: (CloudsLocalEntity object) => [],
        toManyRelations: (CloudsLocalEntity object) => {},
        getId: (CloudsLocalEntity object) => object.id,
        setId: (CloudsLocalEntity object, int id) {
          object.id = id;
        },
        objectToFB: (CloudsLocalEntity object, fb.Builder fbb) {
          fbb.startTable(3);
          fbb.addInt64(0, object.all);
          fbb.addInt64(1, object.id);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final allParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final object = CloudsLocalEntity(all: allParam, id: idParam);

          return object;
        }),
    CoordinateLocalEntity: EntityDefinition<CoordinateLocalEntity>(
        model: _entities[1],
        toOneRelations: (CoordinateLocalEntity object) => [],
        toManyRelations: (CoordinateLocalEntity object) => {},
        getId: (CoordinateLocalEntity object) => object.id,
        setId: (CoordinateLocalEntity object, int id) {
          object.id = id;
        },
        objectToFB: (CoordinateLocalEntity object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addFloat64(0, object.lon);
          fbb.addFloat64(1, object.lat);
          fbb.addInt64(2, object.id);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lonParam =
              const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final latParam =
              const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final object =
              CoordinateLocalEntity(lon: lonParam, lat: latParam, id: idParam);

          return object;
        }),
    MainWeatherInfoLocalEntity: EntityDefinition<MainWeatherInfoLocalEntity>(
        model: _entities[2],
        toOneRelations: (MainWeatherInfoLocalEntity object) => [],
        toManyRelations: (MainWeatherInfoLocalEntity object) => {},
        getId: (MainWeatherInfoLocalEntity object) => object.id,
        setId: (MainWeatherInfoLocalEntity object, int id) {
          object.id = id;
        },
        objectToFB: (MainWeatherInfoLocalEntity object, fb.Builder fbb) {
          final tempOffset =
              object.temp == null ? null : fbb.writeString(object.temp!);
          fbb.startTable(8);
          fbb.addOffset(0, tempOffset);
          fbb.addFloat64(1, object.feelsLike);
          fbb.addFloat64(2, object.tempMin);
          fbb.addFloat64(3, object.tempMax);
          fbb.addInt64(4, object.pressure);
          fbb.addInt64(5, object.humidity);
          fbb.addInt64(6, object.id);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final tempParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 4);
          final feelsLikeParam =
              const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final tempMinParam =
              const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final tempMaxParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 10);
          final pressureParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final humidityParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final object = MainWeatherInfoLocalEntity(
              temp: tempParam,
              feelsLike: feelsLikeParam,
              tempMin: tempMinParam,
              tempMax: tempMaxParam,
              pressure: pressureParam,
              humidity: humidityParam,
              id: idParam);

          return object;
        }),
    SunsetSunriseLocalEntity: EntityDefinition<SunsetSunriseLocalEntity>(
        model: _entities[3],
        toOneRelations: (SunsetSunriseLocalEntity object) => [],
        toManyRelations: (SunsetSunriseLocalEntity object) => {},
        getId: (SunsetSunriseLocalEntity object) => object.id,
        setId: (SunsetSunriseLocalEntity object, int id) {
          object.id = id;
        },
        objectToFB: (SunsetSunriseLocalEntity object, fb.Builder fbb) {
          final countryOffset =
              object.country == null ? null : fbb.writeString(object.country!);
          fbb.startTable(6);
          fbb.addInt64(0, object.type);
          fbb.addInt64(1, object.id);
          fbb.addOffset(2, countryOffset);
          fbb.addInt64(3, object.sunrise);
          fbb.addInt64(4, object.sunset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final typeParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final countryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final sunriseParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final sunsetParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final object = SunsetSunriseLocalEntity(
              type: typeParam,
              id: idParam,
              country: countryParam,
              sunrise: sunriseParam,
              sunset: sunsetParam);

          return object;
        }),
    WeatherDescriptionLocalEntity:
        EntityDefinition<WeatherDescriptionLocalEntity>(
            model: _entities[4],
            toOneRelations: (WeatherDescriptionLocalEntity object) => [],
            toManyRelations: (WeatherDescriptionLocalEntity object) => {},
            getId: (WeatherDescriptionLocalEntity object) => object.id,
            setId: (WeatherDescriptionLocalEntity object, int id) {
              object.id = id;
            },
            objectToFB: (WeatherDescriptionLocalEntity object, fb.Builder fbb) {
              final mainOffset =
                  object.main == null ? null : fbb.writeString(object.main!);
              final descriptionOffset = object.description == null
                  ? null
                  : fbb.writeString(object.description!);
              final iconOffset =
                  object.icon == null ? null : fbb.writeString(object.icon!);
              fbb.startTable(5);
              fbb.addInt64(0, object.id);
              fbb.addOffset(1, mainOffset);
              fbb.addOffset(2, descriptionOffset);
              fbb.addOffset(3, iconOffset);
              fbb.finish(fbb.endTable());
              return object.id;
            },
            objectFromFB: (Store store, ByteData fbData) {
              final buffer = fb.BufferContext(fbData);
              final rootOffset = buffer.derefObject(0);
              final idParam =
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
              final mainParam = const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6);
              final descriptionParam =
                  const fb.StringReader(asciiOptimization: true)
                      .vTableGetNullable(buffer, rootOffset, 8);
              final iconParam = const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10);
              final object = WeatherDescriptionLocalEntity(
                  id: idParam,
                  main: mainParam,
                  description: descriptionParam,
                  icon: iconParam);

              return object;
            }),
    WeatherInfoLocalEntity: EntityDefinition<WeatherInfoLocalEntity>(
        model: _entities[5],
        toOneRelations: (WeatherInfoLocalEntity object) =>
            [object.main, object.wind, object.clouds, object.sys],
        toManyRelations: (WeatherInfoLocalEntity object) => {
              RelInfo<WeatherInfoLocalEntity>.toMany(1, object.id!):
                  object.weather
            },
        getId: (WeatherInfoLocalEntity object) => object.id,
        setId: (WeatherInfoLocalEntity object, int id) {
          object.id = id;
        },
        objectToFB: (WeatherInfoLocalEntity object, fb.Builder fbb) {
          final dtOffset =
              object.dt == null ? null : fbb.writeString(object.dt!);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          fbb.startTable(10);
          fbb.addInt64(0, object.main.targetId);
          fbb.addInt64(1, object.visibility);
          fbb.addInt64(2, object.wind.targetId);
          fbb.addInt64(3, object.clouds.targetId);
          fbb.addOffset(4, dtOffset);
          fbb.addInt64(5, object.sys.targetId);
          fbb.addInt64(6, object.timeZone);
          fbb.addInt64(7, object.id ?? 0);
          fbb.addOffset(8, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final visibilityParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final dtParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final timeZoneParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final object = WeatherInfoLocalEntity(
              visibility: visibilityParam,
              dt: dtParam,
              timeZone: timeZoneParam,
              id: idParam,
              name: nameParam);
          object.main.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.main.attach(store);
          object.wind.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.wind.attach(store);
          object.clouds.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.clouds.attach(store);
          object.sys.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.sys.attach(store);
          InternalToManyAccess.setRelInfo<WeatherInfoLocalEntity>(
              object.weather,
              store,
              RelInfo<WeatherInfoLocalEntity>.toMany(1, object.id!));
          return object;
        }),
    WeatherThemeLocalEntity: EntityDefinition<WeatherThemeLocalEntity>(
        model: _entities[6],
        toOneRelations: (WeatherThemeLocalEntity object) => [],
        toManyRelations: (WeatherThemeLocalEntity object) => {},
        getId: (WeatherThemeLocalEntity object) => object.id,
        setId: (WeatherThemeLocalEntity object, int id) {
          object.id = id;
        },
        objectToFB: (WeatherThemeLocalEntity object, fb.Builder fbb) {
          fbb.startTable(2);
          fbb.addInt64(0, object.id);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = WeatherThemeLocalEntity(id: idParam);

          return object;
        }),
    WindInfoLocalEntity: EntityDefinition<WindInfoLocalEntity>(
        model: _entities[7],
        toOneRelations: (WindInfoLocalEntity object) => [],
        toManyRelations: (WindInfoLocalEntity object) => {},
        getId: (WindInfoLocalEntity object) => object.id,
        setId: (WindInfoLocalEntity object, int id) {
          object.id = id;
        },
        objectToFB: (WindInfoLocalEntity object, fb.Builder fbb) {
          fbb.startTable(4);
          fbb.addFloat64(0, object.speed);
          fbb.addInt64(1, object.deg);
          fbb.addInt64(2, object.id ?? 0);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final speedParam =
              const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final degParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 6);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final object = WindInfoLocalEntity(
              speed: speedParam, deg: degParam, id: idParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [CloudsLocalEntity] entity fields to define ObjectBox queries.
class CloudsLocalEntity_ {
  /// see [CloudsLocalEntity.all]
  static final all =
      QueryIntegerProperty<CloudsLocalEntity>(_entities[0].properties[0]);

  /// see [CloudsLocalEntity.id]
  static final id =
      QueryIntegerProperty<CloudsLocalEntity>(_entities[0].properties[1]);
}

/// [CoordinateLocalEntity] entity fields to define ObjectBox queries.
class CoordinateLocalEntity_ {
  /// see [CoordinateLocalEntity.lon]
  static final lon =
      QueryDoubleProperty<CoordinateLocalEntity>(_entities[1].properties[0]);

  /// see [CoordinateLocalEntity.lat]
  static final lat =
      QueryDoubleProperty<CoordinateLocalEntity>(_entities[1].properties[1]);

  /// see [CoordinateLocalEntity.id]
  static final id =
      QueryIntegerProperty<CoordinateLocalEntity>(_entities[1].properties[2]);
}

/// [MainWeatherInfoLocalEntity] entity fields to define ObjectBox queries.
class MainWeatherInfoLocalEntity_ {
  /// see [MainWeatherInfoLocalEntity.temp]
  static final temp = QueryStringProperty<MainWeatherInfoLocalEntity>(
      _entities[2].properties[0]);

  /// see [MainWeatherInfoLocalEntity.feelsLike]
  static final feelsLike = QueryDoubleProperty<MainWeatherInfoLocalEntity>(
      _entities[2].properties[1]);

  /// see [MainWeatherInfoLocalEntity.tempMin]
  static final tempMin = QueryDoubleProperty<MainWeatherInfoLocalEntity>(
      _entities[2].properties[2]);

  /// see [MainWeatherInfoLocalEntity.tempMax]
  static final tempMax = QueryDoubleProperty<MainWeatherInfoLocalEntity>(
      _entities[2].properties[3]);

  /// see [MainWeatherInfoLocalEntity.pressure]
  static final pressure = QueryIntegerProperty<MainWeatherInfoLocalEntity>(
      _entities[2].properties[4]);

  /// see [MainWeatherInfoLocalEntity.humidity]
  static final humidity = QueryIntegerProperty<MainWeatherInfoLocalEntity>(
      _entities[2].properties[5]);

  /// see [MainWeatherInfoLocalEntity.id]
  static final id = QueryIntegerProperty<MainWeatherInfoLocalEntity>(
      _entities[2].properties[6]);
}

/// [SunsetSunriseLocalEntity] entity fields to define ObjectBox queries.
class SunsetSunriseLocalEntity_ {
  /// see [SunsetSunriseLocalEntity.type]
  static final type = QueryIntegerProperty<SunsetSunriseLocalEntity>(
      _entities[3].properties[0]);

  /// see [SunsetSunriseLocalEntity.id]
  static final id = QueryIntegerProperty<SunsetSunriseLocalEntity>(
      _entities[3].properties[1]);

  /// see [SunsetSunriseLocalEntity.country]
  static final country =
      QueryStringProperty<SunsetSunriseLocalEntity>(_entities[3].properties[2]);

  /// see [SunsetSunriseLocalEntity.sunrise]
  static final sunrise = QueryIntegerProperty<SunsetSunriseLocalEntity>(
      _entities[3].properties[3]);

  /// see [SunsetSunriseLocalEntity.sunset]
  static final sunset = QueryIntegerProperty<SunsetSunriseLocalEntity>(
      _entities[3].properties[4]);
}

/// [WeatherDescriptionLocalEntity] entity fields to define ObjectBox queries.
class WeatherDescriptionLocalEntity_ {
  /// see [WeatherDescriptionLocalEntity.id]
  static final id = QueryIntegerProperty<WeatherDescriptionLocalEntity>(
      _entities[4].properties[0]);

  /// see [WeatherDescriptionLocalEntity.main]
  static final main = QueryStringProperty<WeatherDescriptionLocalEntity>(
      _entities[4].properties[1]);

  /// see [WeatherDescriptionLocalEntity.description]
  static final description = QueryStringProperty<WeatherDescriptionLocalEntity>(
      _entities[4].properties[2]);

  /// see [WeatherDescriptionLocalEntity.icon]
  static final icon = QueryStringProperty<WeatherDescriptionLocalEntity>(
      _entities[4].properties[3]);
}

/// [WeatherInfoLocalEntity] entity fields to define ObjectBox queries.
class WeatherInfoLocalEntity_ {
  /// see [WeatherInfoLocalEntity.main]
  static final main =
      QueryRelationToOne<WeatherInfoLocalEntity, MainWeatherInfoLocalEntity>(
          _entities[5].properties[0]);

  /// see [WeatherInfoLocalEntity.visibility]
  static final visibility =
      QueryIntegerProperty<WeatherInfoLocalEntity>(_entities[5].properties[1]);

  /// see [WeatherInfoLocalEntity.wind]
  static final wind =
      QueryRelationToOne<WeatherInfoLocalEntity, WindInfoLocalEntity>(
          _entities[5].properties[2]);

  /// see [WeatherInfoLocalEntity.clouds]
  static final clouds =
      QueryRelationToOne<WeatherInfoLocalEntity, CloudsLocalEntity>(
          _entities[5].properties[3]);

  /// see [WeatherInfoLocalEntity.dt]
  static final dt =
      QueryStringProperty<WeatherInfoLocalEntity>(_entities[5].properties[4]);

  /// see [WeatherInfoLocalEntity.sys]
  static final sys =
      QueryRelationToOne<WeatherInfoLocalEntity, SunsetSunriseLocalEntity>(
          _entities[5].properties[5]);

  /// see [WeatherInfoLocalEntity.timeZone]
  static final timeZone =
      QueryIntegerProperty<WeatherInfoLocalEntity>(_entities[5].properties[6]);

  /// see [WeatherInfoLocalEntity.id]
  static final id =
      QueryIntegerProperty<WeatherInfoLocalEntity>(_entities[5].properties[7]);

  /// see [WeatherInfoLocalEntity.name]
  static final name =
      QueryStringProperty<WeatherInfoLocalEntity>(_entities[5].properties[8]);

  /// see [WeatherInfoLocalEntity.weather]
  static final weather = QueryRelationToMany<WeatherInfoLocalEntity,
      WeatherDescriptionLocalEntity>(_entities[5].relations[0]);
}

/// [WeatherThemeLocalEntity] entity fields to define ObjectBox queries.
class WeatherThemeLocalEntity_ {
  /// see [WeatherThemeLocalEntity.id]
  static final id =
      QueryIntegerProperty<WeatherThemeLocalEntity>(_entities[6].properties[0]);
}

/// [WindInfoLocalEntity] entity fields to define ObjectBox queries.
class WindInfoLocalEntity_ {
  /// see [WindInfoLocalEntity.speed]
  static final speed =
      QueryDoubleProperty<WindInfoLocalEntity>(_entities[7].properties[0]);

  /// see [WindInfoLocalEntity.deg]
  static final deg =
      QueryIntegerProperty<WindInfoLocalEntity>(_entities[7].properties[1]);

  /// see [WindInfoLocalEntity.id]
  static final id =
      QueryIntegerProperty<WindInfoLocalEntity>(_entities[7].properties[2]);
}
